import './globals.css'


export const metadata = {
  title: 'Quiz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='h-screen overflow-hidden bg-gray-100'>{children}</body>
    </html>
  )
}
