import './globals.css'

export const metadata = {
  title: 'Quiz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='h-screen overflow-hidden bg-slate-900'>
        {children}
        </body>
    </html>
  )
}
