export const Questions = [
  {
    question: "In which language is React.js written?",
    optionA: "Python",
    optionB: "Javascript",
    optionC: "Java",
    optionD: "PHP",
    answer: "B",
  },
  {
    question: "Which of the following ports is the default where webpack-dev-server runs?",
    optionA: "3000",
    optionB: "5000",
    optionC: "3306",
    optionD: "8080",
    answer: "A",
  },
  {
    question: "In MVC, what does React.js act as?",
    optionA: "Model",
    optionB: "View",
    optionC: "Controller",
    optionD: "Middleware",
    answer: "B",
  },
  {
    question: "Using which of the following commands can prevent default behaviour at in react?",
    optionA: "revokeDefault()",
    optionB: "avoidDefault()",
    optionC: "preventDefault()",
    optionD: "None of the above",
    answer: "C",
  },
  {
    question: "What is ReactJS mainly used for building?",
    optionA: "Database",
    optionB: "APIs",
    optionC: "Design Platform",
    optionD: "User Interface",
    answer: "D",
  },
  {
    question: "JSX stands for ______",
    optionA: "Javascript XML",
    optionB: "JSON XML",
    optionC: "Javascript Syntax",
    optionD: "Javascript and Angular",
    answer: "A",
  },
  {
    question: "What company developed React js?",
    optionA: "Apple",
    optionB: "Facebook",
    optionC: "Google",
    optionD: "Twitter",
    answer: "B",
  },
];
